name: CI

on:
	pull_request:
	push:
		branches:
			- main

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v3
			- uses: pnpm/actions-setup@v2
				with: 
					version: 7
			- uses: actions/setup-node@v3
				with:
					node-verstion: 16.x
					cache: "pnpm"
			- run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
			- run: pnpm install --frozen-lockfile
			- run: pnpm run lint && pnpm run build
			- run: echo "🍏 This job's status is ${{ job.status }}."
